name: PythonTests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Running Unittests
      run: |
        python3 TestA1.py
        python3 TestA2.py
        python3 TestA3.py
        python3 TestA4.py
